"""initial schema

Revision ID: 6d0e0dab0529
Revises: 
Create Date: 2026-08-04 14:12:17.821210
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6d0e0dab0529'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_challenges',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_challenges'))
    )
    op.create_index(op.f('ix_otp_challenges_phone'), 'otp_challenges', ['phone'], unique=False)
    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('handle', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('locale', sa.String(length=2), server_default='uz', nullable=False),
    sa.Column('trust_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('responds_within_minutes', sa.Integer(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("locale IN ('uz', 'ru', 'en')", name=op.f('ck_users_locale_supported')),
    sa.CheckConstraint('trust_score BETWEEN 0 AND 100', name=op.f('ck_users_trust_score_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_table('listings',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.Enum('agri', 'livestock', 'machinery', 'transport', 'electronics', 'construction', name='listing_tag'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'reserved', 'closed', name='listing_status'), server_default='active', nullable=False),
    sa.Column('value_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('cash_ok', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_premium', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value_minor >= 0', name=op.f('ck_listings_value_non_negative')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_listings_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listings'))
    )
    op.create_index('ix_listings_feed', 'listings', ['status', 'tag', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('offer', 'match', 'message', 'system', name='notify_kind'), nullable=False),
    sa.Column('target_type', sa.Enum('chat', 'matches', 'verification', 'listing', name='notify_target_type'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=400), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(target_type = 'matches') OR (target_id IS NOT NULL)", name=op.f('ck_notifications_target_id_required')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_feed', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('payment_methods',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('expires', sa.String(length=5), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("last4 ~ '^[0-9]{4}$'", name=op.f('ck_payment_methods_last4_digits')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payment_methods_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_methods'))
    )
    op.create_table('verification_steps',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('step', sa.String(length=40), nullable=False),
    sa.Column('state', sa.Enum('todo', 'pending', 'done', name='verification_state'), server_default='todo', nullable=False),
    sa.Column('hint', sa.String(length=200), nullable=True),
    sa.Column('weight', sa.Integer(), server_default='20', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_verification_steps_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_steps')),
    sa.UniqueConstraint('user_id', 'step', name='uq_verification_step')
    )
    op.create_table('listing_photos',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_listing_photos_listing_id_listings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listing_photos')),
    sa.UniqueConstraint('listing_id', 'position', name='uq_listing_photo_position')
    )
    op.create_table('listing_translations',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_alt', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('condition', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.String(length=80), nullable=False),
    sa.Column('wants_summary', sa.String(length=160), nullable=False),
    sa.CheckConstraint("locale IN ('uz', 'ru', 'en')", name=op.f('ck_listing_translations_locale_supported')),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_listing_translations_listing_id_listings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id', 'locale', name=op.f('pk_listing_translations'))
    )
    op.create_table('listing_wants',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_listing_wants_listing_id_listings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listing_wants'))
    )
    op.create_table('matches',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('my_listing_id', sa.UUID(), nullable=False),
    sa.Column('their_listing_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('my_listing_id <> their_listing_id', name=op.f('ck_matches_distinct_listings')),
    sa.CheckConstraint('score BETWEEN 0 AND 100', name=op.f('ck_matches_score_range')),
    sa.ForeignKeyConstraint(['my_listing_id'], ['listings.id'], name=op.f('fk_matches_my_listing_id_listings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['their_listing_id'], ['listings.id'], name=op.f('fk_matches_their_listing_id_listings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_matches_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('user_id', 'my_listing_id', 'their_listing_id', name='uq_match_pair')
    )
    op.create_table('offers',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'talking', 'accepted', 'declined', 'expired', 'completed', 'disputed', 'refunded', name='offer_status'), server_default='pending', nullable=False),
    sa.Column('cash_delta_minor', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_user_id <> to_user_id', name=op.f('ck_offers_no_self_offer')),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_offers_from_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_offers_listing_id_listings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('fk_offers_to_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers'))
    )
    op.create_index('ix_offers_inbox', 'offers', ['to_user_id', 'status', 'created_at'], unique=False)
    op.create_table('conversations',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('user_a_id', sa.UUID(), nullable=False),
    sa.Column('user_b_id', sa.UUID(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user_a_id <> user_b_id', name=op.f('ck_conversations_distinct_participants')),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_conversations_offer_id_offers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], name=op.f('fk_conversations_user_a_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], name=op.f('fk_conversations_user_b_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('offer_id', name='uq_conversation_offer')
    )
    op.create_table('listing_want_translations',
    sa.Column('want_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.CheckConstraint("locale IN ('uz', 'ru', 'en')", name=op.f('ck_listing_want_translations_locale_supported')),
    sa.ForeignKeyConstraint(['want_id'], ['listing_wants.id'], name=op.f('fk_listing_want_translations_want_id_listing_wants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('want_id', 'locale', name=op.f('pk_listing_want_translations'))
    )
    op.create_table('offer_items',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_offer_items_listing_id_listings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_offer_items_offer_id_offers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id', 'listing_id', name=op.f('pk_offer_items'))
    )
    op.create_table('reviews',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('about_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('author_id <> about_id', name=op.f('ck_reviews_no_self_review')),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['about_id'], ['users.id'], name=op.f('fk_reviews_about_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_reviews_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_reviews_offer_id_offers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('offer_id', 'author_id', name='uq_review_per_deal')
    )
    op.create_index('ix_reviews_about', 'reviews', ['about_id', 'created_at'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_thread', 'messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_thread', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_reviews_about', table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('offer_items')
    op.drop_table('listing_want_translations')
    op.drop_table('conversations')
    op.drop_index('ix_offers_inbox', table_name='offers')
    op.drop_table('offers')
    op.drop_table('matches')
    op.drop_table('listing_wants')
    op.drop_table('listing_translations')
    op.drop_table('listing_photos')
    op.drop_table('verification_steps')
    op.drop_table('payment_methods')
    op.drop_index('ix_notifications_feed', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_listings_feed', table_name='listings')
    op.drop_table('listings')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_challenges_phone'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    # ### end Alembic commands ###
