"""spec alignment: desires, user_type, geo, status names

Revision ID: 9052adff4b59
Revises: 6d0e0dab0529
Create Date: 2026-08-04 14:56:37.103546
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '9052adff4b59'
down_revision: Union[str, None] = '6d0e0dab0529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # listing_status gained the names the business spec uses.
    op.execute("ALTER TYPE listing_status ADD VALUE IF NOT EXISTS 'in_negotiation'")
    op.execute("ALTER TYPE listing_status ADD VALUE IF NOT EXISTS 'completed'")
    op.execute("ALTER TYPE listing_status ADD VALUE IF NOT EXISTS 'archived'")
    op.execute("COMMIT")
    op.execute("UPDATE listings SET status = 'completed' WHERE status = 'closed'")
    op.execute("UPDATE listings SET status = 'in_negotiation' WHERE status = 'reserved'")

    # Created explicitly: add_column will not build the type for us here.
    postgresql.ENUM("individual", "business", name="user_type").create(
        op.get_bind(), checkfirst=True
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desires',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('category', postgresql.ENUM(name='listing_tag', create_type=False), nullable=True),
    sa.Column('min_value_minor', sa.BigInteger(), nullable=True),
    sa.Column('max_value_minor', sa.BigInteger(), nullable=True),
    sa.Column('will_add_cash', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('wants_cash', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('min_value_minor IS NULL OR max_value_minor IS NULL OR min_value_minor <= max_value_minor', name=op.f('ck_desires_value_band_ordered')),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_desires_listing_id_listings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_desires'))
    )
    op.create_index('ix_desires_lookup', 'desires', ['category', 'min_value_minor', 'max_value_minor'], unique=False)
    op.add_column('users', sa.Column('user_type', postgresql.ENUM(name='user_type', create_type=False), server_default='individual', nullable=False))
    op.add_column('users', sa.Column('tax_id', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('free_listings_left', sa.Integer(), server_default='2', nullable=False))
    op.create_unique_constraint(op.f('uq_users_tax_id'), 'users', ['tax_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_tax_id'), 'users', type_='unique')
    op.drop_column('users', 'free_listings_left')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'tax_id')
    op.drop_column('users', 'user_type')
    op.drop_index('ix_desires_lookup', table_name='desires')
    op.drop_table('desires')
    # ### end Alembic commands ###
